### PR TITLE
Added a prophecy sorting function

### PR DESCRIPTION
**Pull request by Xloctis**
Able to read filtersConfig.txt with structures like 

HunterLesson:			Name=Hunter's Lesson				:Prophecies

Tho forgot to add hotfix of 

Currency:			ClassName=StackableCurrency,path!^Essence,path!^Prophecy		:Default Tabs

### CODE REVIEW

**Comment by nymann** [comment]
@Xloctis don't edit .csproj, and what's up with all the spaces? :man_shrugging:

**Comment by Xloctis** [comment]
re downloaded your .csproj but for some reason it tries to commit. Had to make prophecies lowercase and without spaces due to some weird namings "Soils, Worms and Blood" for example.

**Comment by Xloctis** [comment]
Example of sorts
AGraciousMaster:		BaseName=Prophecy,	Name=agraciousmaster		:Prophecies
TwiceEnchanted:		BaseName=Prophecy,	Name=twiceenchanted		:Prophecies

**Comment by zaafar** [comment]
@Xloctis when you say sort, you mean stashing based on prophecy name?

**Pull request merged**
